name: Test Golang
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      # Install dependencies and set up Go
      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: '1.19.2'
          go-version-file: lambda-functions/golang/go.mod
          cache: true

      # Run all the tests
      - name: Test
        working-directory: lambda-functions/golang
        run: go test -v ./...
